// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzpleqbhqixdovrdtfbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6cGxlcWJocWl4ZG92cmR0ZmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTc1ODQsImV4cCI6MjA2Njk3MzU4NH0.NlZiaazHJsdLhi8yN0aEwBWuX8D-EW2qb7PwBd-H2Wc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});